//go:generate /usr/bin/env python ./misc/codegen.py

package curl
/*
#include <curl/curl.h>
#include "compat.h"
*/
import "C"

// CURLcode
const (
	E_UNSUPPORTED_PROTOCOL    = C.CURLE_UNSUPPORTED_PROTOCOL
	E_FAILED_INIT             = C.CURLE_FAILED_INIT
	E_URL_MALFORMAT           = C.CURLE_URL_MALFORMAT
	E_NOT_BUILT_IN            = C.CURLE_NOT_BUILT_IN
	E_COULDNT_RESOLVE_PROXY   = C.CURLE_COULDNT_RESOLVE_PROXY
	E_COULDNT_RESOLVE_HOST    = C.CURLE_COULDNT_RESOLVE_HOST
	E_COULDNT_CONNECT         = C.CURLE_COULDNT_CONNECT
	E_WEIRD_SERVER_REPLY      = C.CURLE_WEIRD_SERVER_REPLY
	E_REMOTE_ACCESS_DENIED    = C.CURLE_REMOTE_ACCESS_DENIED
	E_FTP_ACCEPT_FAILED       = C.CURLE_FTP_ACCEPT_FAILED
	E_FTP_WEIRD_PASS_REPLY    = C.CURLE_FTP_WEIRD_PASS_REPLY
	E_FTP_ACCEPT_TIMEOUT      = C.CURLE_FTP_ACCEPT_TIMEOUT
	E_FTP_WEIRD_PASV_REPLY    = C.CURLE_FTP_WEIRD_PASV_REPLY
	E_FTP_WEIRD_227_FORMAT    = C.CURLE_FTP_WEIRD_227_FORMAT
	E_FTP_CANT_GET_HOST       = C.CURLE_FTP_CANT_GET_HOST
	E_HTTP2                   = C.CURLE_HTTP2
	E_FTP_COULDNT_SET_TYPE    = C.CURLE_FTP_COULDNT_SET_TYPE
	E_PARTIAL_FILE            = C.CURLE_PARTIAL_FILE
	E_FTP_COULDNT_RETR_FILE   = C.CURLE_FTP_COULDNT_RETR_FILE
	E_OBSOLETE20              = C.CURLE_OBSOLETE20
	E_QUOTE_ERROR             = C.CURLE_QUOTE_ERROR
	E_HTTP_RETURNED_ERROR     = C.CURLE_HTTP_RETURNED_ERROR
	E_WRITE_ERROR             = C.CURLE_WRITE_ERROR
	E_OBSOLETE24              = C.CURLE_OBSOLETE24
	E_UPLOAD_FAILED           = C.CURLE_UPLOAD_FAILED
	E_READ_ERROR              = C.CURLE_READ_ERROR
	E_OUT_OF_MEMORY           = C.CURLE_OUT_OF_MEMORY
	E_OPERATION_TIMEDOUT      = C.CURLE_OPERATION_TIMEDOUT
	E_OBSOLETE29              = C.CURLE_OBSOLETE29
	E_FTP_PORT_FAILED         = C.CURLE_FTP_PORT_FAILED
	E_FTP_COULDNT_USE_REST    = C.CURLE_FTP_COULDNT_USE_REST
	E_OBSOLETE32              = C.CURLE_OBSOLETE32
	E_RANGE_ERROR             = C.CURLE_RANGE_ERROR
	E_HTTP_POST_ERROR         = C.CURLE_HTTP_POST_ERROR
	E_SSL_CONNECT_ERROR       = C.CURLE_SSL_CONNECT_ERROR
	E_BAD_DOWNLOAD_RESUME     = C.CURLE_BAD_DOWNLOAD_RESUME
	E_FILE_COULDNT_READ_FILE  = C.CURLE_FILE_COULDNT_READ_FILE
	E_LDAP_CANNOT_BIND        = C.CURLE_LDAP_CANNOT_BIND
	E_LDAP_SEARCH_FAILED      = C.CURLE_LDAP_SEARCH_FAILED
	E_OBSOLETE40              = C.CURLE_OBSOLETE40
	E_FUNCTION_NOT_FOUND      = C.CURLE_FUNCTION_NOT_FOUND
	E_ABORTED_BY_CALLBACK     = C.CURLE_ABORTED_BY_CALLBACK
	E_BAD_FUNCTION_ARGUMENT   = C.CURLE_BAD_FUNCTION_ARGUMENT
	E_OBSOLETE44              = C.CURLE_OBSOLETE44
	E_INTERFACE_FAILED        = C.CURLE_INTERFACE_FAILED
	E_OBSOLETE46              = C.CURLE_OBSOLETE46
	E_TOO_MANY_REDIRECTS      = C.CURLE_TOO_MANY_REDIRECTS
	E_UNKNOWN_OPTION          = C.CURLE_UNKNOWN_OPTION
	E_SETOPT_OPTION_SYNTAX    = C.CURLE_SETOPT_OPTION_SYNTAX
	E_OBSOLETE50              = C.CURLE_OBSOLETE50
	E_OBSOLETE51              = C.CURLE_OBSOLETE51
	E_GOT_NOTHING             = C.CURLE_GOT_NOTHING
	E_SSL_ENGINE_NOTFOUND     = C.CURLE_SSL_ENGINE_NOTFOUND
	E_SSL_ENGINE_SETFAILED    = C.CURLE_SSL_ENGINE_SETFAILED
	E_SEND_ERROR              = C.CURLE_SEND_ERROR
	E_RECV_ERROR              = C.CURLE_RECV_ERROR
	E_OBSOLETE57              = C.CURLE_OBSOLETE57
	E_SSL_CERTPROBLEM         = C.CURLE_SSL_CERTPROBLEM
	E_SSL_CIPHER              = C.CURLE_SSL_CIPHER
	E_PEER_FAILED_VERIFICATION = C.CURLE_PEER_FAILED_VERIFICATION
	E_BAD_CONTENT_ENCODING    = C.CURLE_BAD_CONTENT_ENCODING
	E_OBSOLETE62              = C.CURLE_OBSOLETE62
	E_FILESIZE_EXCEEDED       = C.CURLE_FILESIZE_EXCEEDED
	E_USE_SSL_FAILED          = C.CURLE_USE_SSL_FAILED
	E_SEND_FAIL_REWIND        = C.CURLE_SEND_FAIL_REWIND
	E_SSL_ENGINE_INITFAILED   = C.CURLE_SSL_ENGINE_INITFAILED
	E_LOGIN_DENIED            = C.CURLE_LOGIN_DENIED
	E_TFTP_NOTFOUND           = C.CURLE_TFTP_NOTFOUND
	E_TFTP_PERM               = C.CURLE_TFTP_PERM
	E_REMOTE_DISK_FULL        = C.CURLE_REMOTE_DISK_FULL
	E_TFTP_ILLEGAL            = C.CURLE_TFTP_ILLEGAL
	E_TFTP_UNKNOWNID          = C.CURLE_TFTP_UNKNOWNID
	E_REMOTE_FILE_EXISTS      = C.CURLE_REMOTE_FILE_EXISTS
	E_TFTP_NOSUCHUSER         = C.CURLE_TFTP_NOSUCHUSER
	E_OBSOLETE75              = C.CURLE_OBSOLETE75
	E_OBSOLETE76              = C.CURLE_OBSOLETE76
	E_SSL_CACERT_BADFILE      = C.CURLE_SSL_CACERT_BADFILE
	E_REMOTE_FILE_NOT_FOUND   = C.CURLE_REMOTE_FILE_NOT_FOUND
	E_SSH                     = C.CURLE_SSH
	E_SSL_SHUTDOWN_FAILED     = C.CURLE_SSL_SHUTDOWN_FAILED
	E_AGAIN                   = C.CURLE_AGAIN
	E_SSL_CRL_BADFILE         = C.CURLE_SSL_CRL_BADFILE
	E_SSL_ISSUER_ERROR        = C.CURLE_SSL_ISSUER_ERROR
	E_FTP_PRET_FAILED         = C.CURLE_FTP_PRET_FAILED
	E_RTSP_CSEQ_ERROR         = C.CURLE_RTSP_CSEQ_ERROR
	E_RTSP_SESSION_ERROR      = C.CURLE_RTSP_SESSION_ERROR
	E_FTP_BAD_FILE_LIST       = C.CURLE_FTP_BAD_FILE_LIST
	E_CHUNK_FAILED            = C.CURLE_CHUNK_FAILED
	E_NO_CONNECTION_AVAILABLE = C.CURLE_NO_CONNECTION_AVAILABLE
	E_SSL_PINNEDPUBKEYNOTMATCH = C.CURLE_SSL_PINNEDPUBKEYNOTMATCH
	E_SSL_INVALIDCERTSTATUS   = C.CURLE_SSL_INVALIDCERTSTATUS
	E_HTTP2_STREAM            = C.CURLE_HTTP2_STREAM
	E_RECURSIVE_API_CALL      = C.CURLE_RECURSIVE_API_CALL
	E_AUTH_ERROR              = C.CURLE_AUTH_ERROR
	E_HTTP3                   = C.CURLE_HTTP3
	E_QUIC_CONNECT_ERROR      = C.CURLE_QUIC_CONNECT_ERROR
	E_PROXY                   = C.CURLE_PROXY
	E_SSL_CLIENTCERT          = C.CURLE_SSL_CLIENTCERT
	E_UNRECOVERABLE_POLL      = C.CURLE_UNRECOVERABLE_POLL
	E_OBSOLETE16              = C.CURLE_OBSOLETE16
	E_OBSOLETE10              = C.CURLE_OBSOLETE10
	E_OBSOLETE12              = C.CURLE_OBSOLETE12
	E_FTP_WEIRD_SERVER_REPLY  = C.CURLE_FTP_WEIRD_SERVER_REPLY
	E_SSL_CACERT              = C.CURLE_SSL_CACERT
	E_UNKNOWN_TELNET_OPTION   = C.CURLE_UNKNOWN_TELNET_OPTION
	E_TELNET_OPTION_SYNTAX    = C.CURLE_TELNET_OPTION_SYNTAX
	E_SSL_PEER_CERTIFICATE    = C.CURLE_SSL_PEER_CERTIFICATE
	E_OBSOLETE                = C.CURLE_OBSOLETE
	E_BAD_PASSWORD_ENTERED    = C.CURLE_BAD_PASSWORD_ENTERED
	E_BAD_CALLING_ORDER       = C.CURLE_BAD_CALLING_ORDER
	E_FTP_USER_PASSWORD_INCORRECT = C.CURLE_FTP_USER_PASSWORD_INCORRECT
	E_FTP_CANT_RECONNECT      = C.CURLE_FTP_CANT_RECONNECT
	E_FTP_COULDNT_GET_SIZE    = C.CURLE_FTP_COULDNT_GET_SIZE
	E_FTP_COULDNT_SET_ASCII   = C.CURLE_FTP_COULDNT_SET_ASCII
	E_FTP_WEIRD_USER_REPLY    = C.CURLE_FTP_WEIRD_USER_REPLY
	E_FTP_WRITE_ERROR         = C.CURLE_FTP_WRITE_ERROR
	E_LIBRARY_NOT_FOUND       = C.CURLE_LIBRARY_NOT_FOUND
	E_MALFORMAT_USER          = C.CURLE_MALFORMAT_USER
	E_SHARE_IN_USE            = C.CURLE_SHARE_IN_USE
	E_URL_MALFORMAT_USER      = C.CURLE_URL_MALFORMAT_USER
	E_FTP_ACCESS_DENIED       = C.CURLE_FTP_ACCESS_DENIED
	E_FTP_COULDNT_SET_BINARY  = C.CURLE_FTP_COULDNT_SET_BINARY
	E_FTP_QUOTE_ERROR         = C.CURLE_FTP_QUOTE_ERROR
	E_TFTP_DISKFULL           = C.CURLE_TFTP_DISKFULL
	E_TFTP_EXISTS             = C.CURLE_TFTP_EXISTS
	E_HTTP_RANGE_ERROR        = C.CURLE_HTTP_RANGE_ERROR
	E_FTP_SSL_FAILED          = C.CURLE_FTP_SSL_FAILED
	E_OPERATION_TIMEOUTED     = C.CURLE_OPERATION_TIMEOUTED
	E_HTTP_NOT_FOUND          = C.CURLE_HTTP_NOT_FOUND
	E_HTTP_PORT_FAILED        = C.CURLE_HTTP_PORT_FAILED
	E_FTP_COULDNT_STOR_FILE   = C.CURLE_FTP_COULDNT_STOR_FILE
	E_FTP_PARTIAL_FILE        = C.CURLE_FTP_PARTIAL_FILE
	E_FTP_BAD_DOWNLOAD_RESUME = C.CURLE_FTP_BAD_DOWNLOAD_RESUME
	E_LDAP_INVALID_URL        = C.CURLE_LDAP_INVALID_URL
	E_CONV_REQD               = C.CURLE_CONV_REQD
	E_CONV_FAILED             = C.CURLE_CONV_FAILED
	E_ALREADY_COMPLETE        = C.CURLE_ALREADY_COMPLETE
)

// easy.Setopt(flag, ...)
const (
	OPT_ENCODING                  = C.CURLOPT_ENCODING
	OPT_FILE                      = C.CURLOPT_FILE
	OPT_INFILE                    = C.CURLOPT_INFILE
	OPT_WRITEHEADER               = C.CURLOPT_WRITEHEADER
	OPT_WRITEINFO                 = C.CURLOPT_WRITEINFO
	OPT_CLOSEPOLICY               = C.CURLOPT_CLOSEPOLICY
	OPT_PROGRESSDATA              = C.CURLOPT_PROGRESSDATA
	OPT_POST301                   = C.CURLOPT_POST301
	OPT_SSLKEYPASSWD              = C.CURLOPT_SSLKEYPASSWD
	OPT_FTPAPPEND                 = C.CURLOPT_FTPAPPEND
	OPT_FTPLISTONLY               = C.CURLOPT_FTPLISTONLY
	OPT_FTP_SSL                   = C.CURLOPT_FTP_SSL
	OPT_SSLCERTPASSWD             = C.CURLOPT_SSLCERTPASSWD
	OPT_KRB4LEVEL                 = C.CURLOPT_KRB4LEVEL
	OPT_FTP_RESPONSE_TIMEOUT      = C.CURLOPT_FTP_RESPONSE_TIMEOUT
	OPT_RTSPHEADER                = C.CURLOPT_RTSPHEADER
)

// easy.Getinfo(flag)
const (
	INFO_TEXT                 = C.CURLINFO_TEXT
	INFO_EFFECTIVE_URL        = C.CURLINFO_EFFECTIVE_URL
	INFO_RESPONSE_CODE        = C.CURLINFO_RESPONSE_CODE
	INFO_TOTAL_TIME           = C.CURLINFO_TOTAL_TIME
	INFO_NAMELOOKUP_TIME      = C.CURLINFO_NAMELOOKUP_TIME
	INFO_CONNECT_TIME         = C.CURLINFO_CONNECT_TIME
	INFO_PRETRANSFER_TIME     = C.CURLINFO_PRETRANSFER_TIME
	INFO_SIZE_UPLOAD_T        = C.CURLINFO_SIZE_UPLOAD_T
	INFO_SIZE_DOWNLOAD_T      = C.CURLINFO_SIZE_DOWNLOAD_T
	INFO_SPEED_DOWNLOAD_T     = C.CURLINFO_SPEED_DOWNLOAD_T
	INFO_SPEED_UPLOAD_T       = C.CURLINFO_SPEED_UPLOAD_T
	INFO_HEADER_SIZE          = C.CURLINFO_HEADER_SIZE
	INFO_REQUEST_SIZE         = C.CURLINFO_REQUEST_SIZE
	INFO_SSL_VERIFYRESULT     = C.CURLINFO_SSL_VERIFYRESULT
	INFO_FILETIME             = C.CURLINFO_FILETIME
	INFO_FILETIME_T           = C.CURLINFO_FILETIME_T
	INFO_CONTENT_LENGTH_DOWNLOAD_T = C.CURLINFO_CONTENT_LENGTH_DOWNLOAD_T
	INFO_CONTENT_LENGTH_UPLOAD_T = C.CURLINFO_CONTENT_LENGTH_UPLOAD_T
	INFO_STARTTRANSFER_TIME   = C.CURLINFO_STARTTRANSFER_TIME
	INFO_CONTENT_TYPE         = C.CURLINFO_CONTENT_TYPE
	INFO_REDIRECT_TIME        = C.CURLINFO_REDIRECT_TIME
	INFO_REDIRECT_COUNT       = C.CURLINFO_REDIRECT_COUNT
	INFO_PRIVATE              = C.CURLINFO_PRIVATE
	INFO_HTTP_CONNECTCODE     = C.CURLINFO_HTTP_CONNECTCODE
	INFO_HTTPAUTH_AVAIL       = C.CURLINFO_HTTPAUTH_AVAIL
	INFO_PROXYAUTH_AVAIL      = C.CURLINFO_PROXYAUTH_AVAIL
	INFO_OS_ERRNO             = C.CURLINFO_OS_ERRNO
	INFO_NUM_CONNECTS         = C.CURLINFO_NUM_CONNECTS
	INFO_SSL_ENGINES          = C.CURLINFO_SSL_ENGINES
	INFO_COOKIELIST           = C.CURLINFO_COOKIELIST
	INFO_FTP_ENTRY_PATH       = C.CURLINFO_FTP_ENTRY_PATH
	INFO_REDIRECT_URL         = C.CURLINFO_REDIRECT_URL
	INFO_PRIMARY_IP           = C.CURLINFO_PRIMARY_IP
	INFO_APPCONNECT_TIME      = C.CURLINFO_APPCONNECT_TIME
	INFO_CERTINFO             = C.CURLINFO_CERTINFO
	INFO_CONDITION_UNMET      = C.CURLINFO_CONDITION_UNMET
	INFO_RTSP_SESSION_ID      = C.CURLINFO_RTSP_SESSION_ID
	INFO_RTSP_CLIENT_CSEQ     = C.CURLINFO_RTSP_CLIENT_CSEQ
	INFO_RTSP_SERVER_CSEQ     = C.CURLINFO_RTSP_SERVER_CSEQ
	INFO_RTSP_CSEQ_RECV       = C.CURLINFO_RTSP_CSEQ_RECV
	INFO_PRIMARY_PORT         = C.CURLINFO_PRIMARY_PORT
	INFO_LOCAL_IP             = C.CURLINFO_LOCAL_IP
	INFO_LOCAL_PORT           = C.CURLINFO_LOCAL_PORT
	INFO_ACTIVESOCKET         = C.CURLINFO_ACTIVESOCKET
	INFO_TLS_SSL_PTR          = C.CURLINFO_TLS_SSL_PTR
	INFO_HTTP_VERSION         = C.CURLINFO_HTTP_VERSION
	INFO_PROXY_SSL_VERIFYRESULT = C.CURLINFO_PROXY_SSL_VERIFYRESULT
	INFO_SCHEME               = C.CURLINFO_SCHEME
	INFO_TOTAL_TIME_T         = C.CURLINFO_TOTAL_TIME_T
	INFO_NAMELOOKUP_TIME_T    = C.CURLINFO_NAMELOOKUP_TIME_T
	INFO_CONNECT_TIME_T       = C.CURLINFO_CONNECT_TIME_T
	INFO_PRETRANSFER_TIME_T   = C.CURLINFO_PRETRANSFER_TIME_T
	INFO_STARTTRANSFER_TIME_T = C.CURLINFO_STARTTRANSFER_TIME_T
	INFO_REDIRECT_TIME_T      = C.CURLINFO_REDIRECT_TIME_T
	INFO_APPCONNECT_TIME_T    = C.CURLINFO_APPCONNECT_TIME_T
	INFO_RETRY_AFTER          = C.CURLINFO_RETRY_AFTER
	INFO_EFFECTIVE_METHOD     = C.CURLINFO_EFFECTIVE_METHOD
	INFO_PROXY_ERROR          = C.CURLINFO_PROXY_ERROR
	INFO_REFERER              = C.CURLINFO_REFERER
	INFO_CAINFO               = C.CURLINFO_CAINFO
	INFO_CAPATH               = C.CURLINFO_CAPATH
	INFO_LASTONE              = C.CURLINFO_LASTONE
	INFO_HTTP_CODE            = C.CURLINFO_HTTP_CODE
)

// Auth
const (
	AUTH_NONE                      = C.CURLAUTH_NONE & (1<<32 - 1)
	AUTH_BASIC                     = C.CURLAUTH_BASIC & (1<<32 - 1)
	AUTH_DIGEST                    = C.CURLAUTH_DIGEST & (1<<32 - 1)
	AUTH_NEGOTIATE                 = C.CURLAUTH_NEGOTIATE & (1<<32 - 1)
	AUTH_GSSNEGOTIATE              = C.CURLAUTH_GSSNEGOTIATE & (1<<32 - 1)
	AUTH_GSSAPI                    = C.CURLAUTH_GSSAPI & (1<<32 - 1)
	AUTH_NTLM                      = C.CURLAUTH_NTLM & (1<<32 - 1)
	AUTH_DIGEST_IE                 = C.CURLAUTH_DIGEST_IE & (1<<32 - 1)
	AUTH_NTLM_WB                   = C.CURLAUTH_NTLM_WB & (1<<32 - 1)
	AUTH_BEARER                    = C.CURLAUTH_BEARER & (1<<32 - 1)
	AUTH_AWS_SIGV4                 = C.CURLAUTH_AWS_SIGV4 & (1<<32 - 1)
	AUTH_ONLY                      = C.CURLAUTH_ONLY & (1<<32 - 1)
	AUTH_ANY                       = C.CURLAUTH_ANY & (1<<32 - 1)
	AUTH_ANYSAFE                   = C.CURLAUTH_ANYSAFE & (1<<32 - 1)
)

// generated ends
